### ISSUE TITLE
Windows speller builds fail often

### ISSUE THREAD

**Issue by snomos** [divvun/taskcluster-gha#12]
The Windows specific build steps (including signing) is too unreliable. It fails more often than not, with the following error:

```
C:\Users\task_172550336727445>python -u C:\Users\task_172550336727445\AbdITRVTRrOo4GL3RcvXtQ\ci\runner.py C:\Users\task_172550336727445\AbdITRVTRrOo4GL3RcvXtQ\AbdITRVTRrOo4GL3RcvXtQ.json" 
Running clone
Running  ['pwsh', '-c', 'node ${HOME}/${TASK_ID}/_temp/actions/checkout@releases/v4.0.0/dist/index.js']
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\task_172550336727445\AbdITRVTRrOo4GL3RcvXtQ\ci\runner.py", line 585, in <module>
    asyncio.run(main())
  File "C:\Users\task_172550336727445\python3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\task_172550336727445\python3\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\task_172550336727445\AbdITRVTRrOo4GL3RcvXtQ\ci\runner.py", line 570, in main
    await run_action(name, action)
  File "C:\Users\task_172550336727445\AbdITRVTRrOo4GL3RcvXtQ\ci\runner.py", line 325, in run_action
    process = await asyncio.subprocess.create_subprocess_exec(
  File "C:\Users\task_172550336727445\python3\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\task_172550336727445\python3\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\task_172550336727445\python3\lib\asyncio\windows_events.py", line 389, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\task_172550336727445\python3\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\task_172550336727445\python3\lib\asyncio\windows_events.py", line 885, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\task_172550336727445\python3\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\task_172550336727445\python3\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\task_172550336727445\python3\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
[taskcluster 2024-09-05T05:11:38.878Z]    Exit Code: 1
[taskcluster 2024-09-05T05:11:38.878Z]    User Time: 15.625ms
[taskcluster 2024-09-05T05:11:38.878Z]  Kernel Time: 125ms
[taskcluster 2024-09-05T05:11:38.878Z]    Wall Time: 1m30.6099504s
[taskcluster 2024-09-05T05:11:38.878Z]       Result: FAILED
[taskcluster 2024-09-05T05:11:38.879Z] === Task Finished ===
[taskcluster 2024-09-05T05:11:38.879Z] Task Duration: 1m30.617562s
[taskcluster:error] exit status 1
```

This is quite annoying, as we can't rely on Windows builds going through. It impacts our ability to make releases.

**Comment by snomos** [comment]
With the build machine fix discussed in the meeting yesterday the problem seems gone. I'll close this one.
